### ISSUE TITLE
Pull request: mobile number in store details

### ISSUE THREAD

**Issue by elcreativo** [tastaturberuf-contao-modules/anyStores#14]
Ich habe zu den Store Details die Mobilfunknummer hinzugefügt. Die Github App lässt mich keinen Pullrequest setzen. Ist das aktuell gesperrt?

**Comment by Tastaturberuf** [comment]
Nö alles auf Standard.

**Comment by Tastaturberuf** [comment]
Ich glaube man muss vorher forken, nicht klonen. Bin aber auch recht neu mit Git unterwegs.
