### ISSUE TITLE
add expert settings to store details

### ISSUE THREAD

**Issue by elcreativo** [tastaturberuf-contao-modules/anyStores#27]
![bildschirmfoto 2015-03-19 um 11 54 14](https://cloud.githubusercontent.com/assets/1964186/6729027/d866f1e6-ce2e-11e4-8372-543fec754a3d.png)

**Comment by Tastaturberuf** [comment]
https://github.com/tastaturberuf-contao-modules/anyStores/blob/master/dca/tl_module.php#L35
