### ISSUE TITLE
change page title with module "anyStores Details"

### ISSUE THREAD

**Issue by elcreativo** [tastaturberuf-contao-modules/anyStores#29]
Aktuell liegt das Modul "anyStores Details" in der Seite "Mitglieder Details". 
Gibt es eine Möglichkeit über das Modul den Seitentitel aus dem Mitgliederdaten einzufügen und nicht den Namen der Seite in dem das Modul liegt (In diesem Fall heißt die Seite "Mitglieder Details" und nicht "Name des Mitgliedes"?

Bei dem News Reader Funktioniert das bereits so.

**Comment by Tastaturberuf** [comment]
Duplicate #25 

Geht aktuell mit diesem Snippet im Template ```mod_anystores_details```:

```PHP
<?php
$strAlias = \Input::get('auto_item') ? \Input::get('auto_item') : \Input::get('store');
if ( ($objStore = AnyStoresModel::findPublishedByIdOrAlias($strAlias)) !== null )
{
    $GLOBALS['objPage']->title = $objStore->name;
}
?>
```

**Comment by elcreativo** [comment]
Dann bekomme ich folgenden Fehler raus :

```
Fatal error: Cannot redeclare class Tastaturberuf\AnyStoresModel in /www/htdocs/system/modules/anyStores/models/AnyStoresModel.php on line 210

**Comment by Tastaturberuf** [comment]
Schick mir mal bitte das Template per E-Mail.

**Comment by Tastaturberuf** [comment]
Und welche  Contao- und anyStores-Version?
