### ISSUE TITLE
Landeskarten

### ISSUE THREAD

**Issue by overheaddesign** [tastaturberuf-contao-modules/anyStores#5]
Es wäre noch gut das wenn man schon auswählen kann das der Händler in Deutschland ist, dass es auch eine Karte gibt wo alle die in diesem Land sind auch auf einer Karte komplett anzuzeigen geht. per Point die man noch separat stylen (also css Klasse für jeden Händler hinzufügbar)

**Comment by Tastaturberuf** [comment]
Added in https://github.com/tastaturberuf-contao-modules/anyStores/commit/545ad0f6e485ef8d427e01e92e376c18d0dd3d26

**Comment by Tastaturberuf** [comment]
Added in https://github.com/tastaturberuf-contao-modules/anyStores/commit/2bf07c7f04b5e3ef4a36177ff5d27c428bd93157
